### ISSUE TITLE
"Delete Task" inside task details not working

### ISSUE THREAD

**Issue by asimdhakal** [anilmndl/taskmgmt#113]
Attempting to delete a task under task detail throws an error
![image](https://user-images.githubusercontent.com/17816478/38059274-10da66e4-32a3-11e8-8b51-339735ad0605.png)

**Comment by SanRIZZ** [comment]
The issue was someone was using task.deleted when we didn't had an enum with deleted name.
I as well as fixed the problem with deleted task showing up in the list.
I also fixed the error in edit of task. The customer list wasn't passed in edit. Fixed it.
Only bug in task is, it has is the completed and my task stuffs not working yet.
I am on it.
