### ISSUE TITLE
Help needed regarding the comment in Task 

### ISSUE THREAD

**Issue by pathsush** [anilmndl/taskmgmt#139]
When I want to post a comment in a task detail page it throws an error like this. I am not being able to solve the issue. 

![capture](https://user-images.githubusercontent.com/32222516/38417394-5f4ecb36-3955-11e8-9eb8-5d7260e8c6ba.PNG)

**Comment by Carpbra3** [comment]
I'm looking at this right now. I am trying to figure out how you are getting to that point because I have found some issues creating a task, which I am looking into now. 

Also, a side note from a user's perspective. I had a hard time figuring out creating a new user. I see that Middle Name is not a nullable field. I would recommend making that field nullable.

**Comment by Carpbra3** [comment]
I'm going to make the assumption that you have already removed or changed this line of code from your local copy. This was the next problem I ran into. I'm not clear what the flag property is for, but it has already been commented out on the domain class. Let me know if that isn't correct.

![image](https://user-images.githubusercontent.com/17454975/38438120-c75b1f72-3996-11e8-89fb-9f9a6a6e9d6b.png)

**Comment by Carpbra3** [comment]
Okay, so I have moved passed this issue ... the next issue I see is how this select box element is created. With this field the way it is, it is trying to pass a string (taskTypes.title) with the form submission. Not sure if you have already resolved this yet because the error I am getting here is different than your original error. Let me know if you have resolved this and I can continue to find what your specific issue is. This is a screenshot of our task/edit page

![image](https://user-images.githubusercontent.com/17454975/38438434-c4f4ba76-3997-11e8-8c0b-15a3142e2e71.png)
