### ISSUE TITLE
Pull And Push

### ISSUE THREAD

**Issue by simkkish** [anilmndl/taskmgmt#26]
Hi Professor,
We group member have confusion with what to do after the our personal part is done. If I am not wrong "we are supposed to push to develop after our code in fully working". Please let us know what is the good thing to know.
--
Kishor Simkhada

**Comment by anilmndl** [comment]
The final goal is to merge your code with the 'develop' branch and push all changes to the repository. You have to make sure the develop branch is fully functional and it compiles without any error. However, if you are not careful, it will create merge conflicts. 

My suggested process is as follows.

1. Checkout to the 'develop' branch and pull any changes.
2. Checkout to your personal branch and merge the 'develop' branches.
3. Fix any merge issue in this step and commit the merge.
4. Push your changes to the repo. Your changes should be visible in the GitHub.
5. Checkout the develop branch. Make sure no additional changes were made since your last pull. If there were new changes, goto step 1 and repeat
6. Merge your personal branch to 'develop' branch.
7. Push the develop branch.
