### ISSUE TITLE
database connection failed

### ISSUE THREAD

**Issue by pathsush** [anilmndl/taskmgmt#45]
![capture](https://user-images.githubusercontent.com/32222516/36857235-3df0f0fe-1d35-11e8-951d-1b254c91e9c0.PNG)

I am working on the milestone 2. I make the new domain for it called user with the new controller. But it is not connecting to the database. I checked application.yml. I checked the syntax near user too. It is fine Everything is good. Is there any specific thing i need to make it correct so that it will work.

**Comment by anilmndl** [comment]
I do not think your database connection failed. If that was the case, you app would not even compile but it has compiled successfully in your case. 

Read the ERROR message carefully. It says, it was not able to drop the table user. Since you have create-drop in your application.yml file, its trying to drop all the tables in your database first and then create necessary tables again. However, Grails was not successful in dropping the table. 

In this case you can manually drop the table and start the application.

**Comment by pathsush** [comment]
It works !!
Thank you!!
