### ISSUE TITLE
Issue: couldn't fix validation error while making association between task and task type. 

### ISSUE THREAD

**Issue by pathsush** [anilmndl/taskmgmt#49]
https://github.com/anilmndl/taskmgmt/blob/9e921cec9a22e81e7dd0530e3c6de642e71bb23d/grails-app/services/taskmgmt/TaskService.groovy#L11

![capture](https://user-images.githubusercontent.com/32222516/36874315-b143c3aa-1d68-11e8-8d75-b870de3e22da.PNG)

**Comment by TatoProgramming** [comment]
The error is being thrown during saving due to ```failOnError: true```. I would pay attention to what values are being passed to controller from the view. Grails is doing some magic here and cant figure out how to map "taskmgmt.TaskType : 1" to a TaskType. You can try using ```task.errors``` to view the errors after ```task.validate()```. If you can not figure it out by class we can investigate more.

**Comment by anilmndl** [comment]
The code here is not correct for Grails to bind taskType information to a specific task. 
Hint: you have similar issue you had with blog and author.id

https://github.com/anilmndl/taskmgmt/blob/9e921cec9a22e81e7dd0530e3c6de642e71bb23d/grails-app/views/task/create.gsp#L18

In order to solve the issue, I would put a break point on this line and find out what values you have in _params_ and _task_ variables.

https://github.com/anilmndl/taskmgmt/blob/9e921cec9a22e81e7dd0530e3c6de642e71bb23d/grails-app/controllers/taskmgmt/TaskController.groovy#L51

**Comment by pathsush** [comment]
Finally, it worked. 
Thanks
