### ISSUE TITLE
Why do we have date in dateCreated even thought we never explicity filled data on it?

### ISSUE THREAD

**Issue by shreamar** [anilmndl/taskmgmt#50]
https://github.com/anilmndl/taskmgmt/blob/c638d12dc5172321c9eed0386f51f19b91359f51/grails-app/services/taskmgmt/RoleService.groovy#L8

Even though we don't have any code in this save method that tells it to fill dateCreated with data, why is dateCreated auto filled? I know it's not nullable, is that why groovy does it for us?

I'm obviously missing something in here.

**Comment by SanRIZZ** [comment]
Well i believe it was you who made that role CRUD. just make a role.DateCreated = new Date()

**Comment by shreamar** [comment]
https://github.com/anilmndl/taskmgmt/blob/c638d12dc5172321c9eed0386f51f19b91359f51/grails-app/services/taskmgmt/TaskService.groovy#L11

Even this one doesn't have it. So my question is not why it's not working, its, why is it still working?

**Comment by SanRIZZ** [comment]
because in task, some one went ahead and set the dateCreated nullable:true

**Comment by shreamar** [comment]
Yeah, I see that. But it doesn't explain why dateCreated has data on it when it was never initialized.

**Comment by anilmndl** [comment]
Its not Groovy but the Grails framework does that.

[http://docs.grails.org/3.0.17/ref/Database%20Mapping/autoTimestamp.html](http://docs.grails.org/3.0.17/ref/Database%20Mapping/autoTimestamp.html)

This is one example of configuration vs convention benefit we get for free. Since the dateCreated matched the convention defined in the Grails, it works automagically.

This also explains if you change the name from dateModified to lastUpdated, Grails will do its magic on that property as well.
